spring:
  #esto permite agregar un parametro en la url para poder escoger el formato en que se va a ver la informacion (PDF, XML, JSON, etc...)
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        pdf: application/pdf
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        csv: text/csv
        xml: application/xml
        json: application/json
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost/db_springboot?serverTimezone=America/Mexico_City
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: debug